# Generated by Django 4.2.28 on 2026-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whctools', '0009_welcomemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acl',
            name='skill_sets',
        )
    ]
